### ISSUE TITLE
[Discussion] Jinja usage for zone data dict vs ansible `vars`

### ISSUE THREAD

**Issue by nE0sIghT** [ganto/ansible-gdnsd#28]
Hello!

First of all thanks for your project - your ideas (from blog post [1]) related to zonefile handling are used in several projects.

Our team had some discussion about your way of data handling in Jinja templates:

```
{% set _zone_data = {} %}
{% set _ = _zone_data.update({'ttl': gdnsd__include_zone.ttl|d(gdnsd__ttl)}) %}
```

It was written 8 years ago and syntactically not obvious on 1st eye tbh.

Just wonder what do you think about using `vars` to handle dict in the Ansible task?

Eg

```
- name: '{{ gdnsd__include_zone.domain }} - Generate forward zone file'
  ansible.builtin.template:
    src: 'zone.j2'
    ...
  vars:
    _zone_data:
      ttl: "gdnsd__include_zone.ttl|d(gdnsd__ttl)"
      ...
```

[1] https://linuxmonk.ch/wordpress/index.php/2016/managing-dns-zones-with-ansible/
